sudo: true

language: bash

services:
  - docker

env:
  global:
    - DEBIAN_FRONTEND="noninteractive"
    - DOCKERHUB_LIVE="taisun/dev_cloud9"

jobs:
  include:
    - stage: "Build Containers"
      name: "Build NodeJS"
      before_install:
        - /bin/bash pre_install
      script: ./builder.sh Node.js dockerfiles/nodejs/
    - script: ./builder.sh Python dockerfiles/python/
      before_install:
        - /bin/bash pre_install
      name: "Build Python"
    - script: ./builder.sh Go dockerfiles/go/
      before_install:
        - /bin/bash pre_install
      name: "Build Go"
    - script: ./builder.sh Ruby dockerfiles/ruby/
      before_install:
        - /bin/bash pre_install
      name: "Build Ruby"
    - script: ./builder.sh Docker dockerfiles/docker/
      before_install:
        - /bin/bash pre_install
      name: "Build Docker"
